const { spawnSync } = require('child_process'); 

const languagePairsSupported = new Set([
  'hrv-eng',
  'fin-por',
  'fin-bul',
  'fra-bul',
  'deu-swe',
  'fin-swe',
  'jpn-rus',
  'wol-fra',
  'fra-pol',
  'eng-deu',
  'deu-nld',
  'por-eng',
  'spa-deu',
  'ces-eng',
  'swe-fin',
  'eng-pol',
  'pol-nor',
  'eng-rom',
  'eng-fra',
  'fin-ell',
  'eng-lit',
  'ckb-kmr',
  'ita-eng',
  'pol-eng',
  'gle-eng',
  'eng-tur',
  'gle-pol',
  'pol-deu',
  'fra-spa',
  'lit-eng',
  'eng-jpn',
  'ara-eng',
  'nld-ita',
  'eng-lat',
  'eng-hun',
  'ita-jpn',
  'dan-eng',
  'hun-eng',
  'pol-gle',
  'fra-fin',
  'nld-swe',
  'nld-eng',
  'deu-kur',
  'deu-spa',
  'eng-afr',
  'eng-swe',
  'jpn-deu',
  'epo-eng',
  'pol-nld',
  'lat-deu',
  'eng-cym',
  'por-spa',
  'eng-spa',
  'swe-tur',
  'tur-eng',
  'tur-deu',
  'pol-fra',
  'eng-por',
  'ita-pol',
  'eng-ces',
  'deu-tur',
  'fra-jpn',
  'cym-eng',
  'bre-fra',
  'jpn-fra',
  'nld-deu',
  'eng-nld',
  'deu-por',
  'eng-hrv',
  'mkd-bul',
  'swe-eng',
  'pol-spa',
  'jpn-eng',
  'eng-ell',
  'ita-por',
  'pol-swe',
  'pol-fin',
  'kur-tur',
  'ita-swe',
  'eng-swh',
  'kha-eng',
  'fin-eng',
  'eng-hin',
  'spa-eng',
  'afr-eng',
  'ita-fin',
  'eng-fin',
  'fra-ita',
  'deu-rus',
  'deu-bul',
  'deu-pol',
  'srp-eng',
  'kur-deu',
  'spa-por',
  'swe-pol',
  'swe-rus',
  'nld-spa',
  'swh-pol',
  'oci-cat',
  'ita-rus',
  'fra-ell',
  'eng-srp',
  'fra-tur',
  'fra-eng',
  'ita-ell',
  'kur-eng',
  'swe-deu',
  'swe-fra',
  'swe-lat',
  'swe-ell',
  'eng-rus',
  'pol-por',
  'gla-deu',
  'eng-ita',
  'pol-ita',
  'fra-swe',
  'isl-eng',
  'swe-spa',
  'nno-nob',
  'swe-ita',
  'fra-deu',
  'fin-ita',
  'nld-fra',
  'eng-ara',
  'slk-eng',
  'fra-por',
  'spa-ast',
  'fin-jpn',
  'deu-ita',
  'swh-eng',
  'fin-nor',
  'fra-nld',
  'lat-eng',
  'eng-bul',
  'deu-fra',
  'swe-bul',
  'deu-eng',
  'pol-rus',
  'ita-deu',
  'eng-gle',
  'swe-por',
  'afr-deu',
  'por-deu',
  'fra-bre',
  'san-deu',
  'kha-deu',
  'fra-rus',
  'pol-ell'
]);

const languagePairsList = [
  { value: 'hrv-eng', title: 'Croatian-English' },
  { value: 'fin-por', title: 'suomi-português' },
  { value: 'fin-bul', title: 'suomi-български език' },
  { value: 'fra-bul', title: 'français-български език' },
  { value: 'deu-swe', title: 'Deutsch-Svenska' },
  { value: 'fin-swe', title: 'suomi-Svenska' },
  { value: 'jpn-rus', title: 'Japanese-Russian' },
  { value: 'wol-fra', title: 'Wolof-French' },
  { value: 'fra-pol', title: 'français-język polski' },
  { value: 'eng-deu', title: 'English-German' },
  { value: 'deu-nld', title: 'German-Dutch' },
  { value: 'por-eng', title: 'Portuguese-English' },
  { value: 'spa-deu', title: 'Spanish-German' },
  { value: 'ces-eng', title: 'Czech-English' },
  { value: 'swe-fin', title: 'Svenska-suomi' },
  { value: 'eng-pol', title: 'English-Polish' },
  { value: 'pol-nor', title: 'język polski-Norsk' },
  { value: 'eng-rom', title: 'English-Romanian' },
  { value: 'eng-fra', title: 'English-French' },
  { value: 'fin-ell', title: 'suomi-ελληνικά' },
  { value: 'eng-lit', title: 'English-Lithuanian' },
  { value: 'ckb-kmr', title: 'Sorani-Kurmanji' },
  { value: 'ita-eng', title: 'Italian-English' },
  { value: 'pol-eng', title: 'język polski-English' },
  { value: 'gle-eng', title: 'Irish-English' },
  { value: 'eng-tur', title: 'English-Turkish' },
  { value: 'gle-pol', title: 'Irish-Polish' },
  { value: 'pol-deu', title: 'język polski-Deutsch' },
  { value: 'fra-spa', title: 'français-español' },
  { value: 'lit-eng', title: 'Lithuanian-English' },
  { value: 'eng-jpn', title: 'English-日本語 (にほんご)' },
  { value: 'ara-eng', title: 'Arabic-English' },
  { value: 'nld-ita', title: 'Nederlands-italiano' },
  { value: 'eng-lat', title: 'English-Latin' },
  { value: 'eng-hun', title: 'English-Hungarian' },
  { value: 'ita-jpn', title: 'italiano-日本語 (にほんご)' },
  { value: 'dan-eng', title: 'Danish-English' },
  { value: 'hun-eng', title: 'Hungarian-English' },
  { value: 'pol-gle', title: 'Polish-Irish' },
  { value: 'fra-fin', title: 'français-suomi' },
  { value: 'nld-swe', title: 'Nederlands-Svenska' },
  { value: 'nld-eng', title: 'Dutch-English' },
  { value: 'deu-kur', title: 'German-Kurdish' },
  { value: 'deu-spa', title: 'Deutsch-español' },
  { value: 'eng-afr', title: 'English-Afrikaans' },
  { value: 'eng-swe', title: 'English-Swedish' },
  { value: 'jpn-deu', title: 'Japanese-German' },
  { value: 'epo-eng', title: 'Esperanto-English' },
  { value: 'pol-nld', title: 'język polski-Nederlands' },
  { value: 'lat-deu', title: 'Lateinisch-Deutsch' },
  { value: 'eng-cym', title: 'Eurfa Saesneg }, English-Welsh' },
  { value: 'por-spa', title: 'português-español' },
  { value: 'eng-spa', title: 'English-Spanish' },
  { value: 'swe-tur', title: 'Svenska-Türkçe' },
  { value: 'tur-eng', title: 'Turkish-English' },
  { value: 'tur-deu', title: 'Turkish-German' },
  { value: 'pol-fra', title: 'język polski-français' },
  { value: 'eng-por', title: 'English-Portuguese' },
  { value: 'ita-pol', title: 'italiano-język polski' },
  { value: 'eng-ces', title: 'English-Czech' },
  { value: 'deu-tur', title: 'German-Turkish' },
  { value: 'fra-jpn', title: 'français-日本語 (にほんご)' },
  { value: 'cym-eng', title: 'Eurfa Cymraeg }, Welsh-English' },
  { value: 'bre-fra', title: 'Breton-French' },
  { value: 'jpn-fra', title: 'Japanese-French' },
  { value: 'nld-deu', title: 'Dutch-German' },
  { value: 'eng-nld', title: 'English-Dutch' },
  { value: 'deu-por', title: 'German-Portuguese' },
  { value: 'eng-hrv', title: 'English-Croatian' },
  { value: 'mkd-bul', title: 'Macedonian-Bulgarian' },
  { value: 'swe-eng', title: 'Swedish-English' },
  { value: 'pol-spa', title: 'język polski-español' },
  { value: 'jpn-eng', title: 'Japanese-English' },
  { value: 'eng-ell', title: 'English-Modern Greek' },
  { value: 'ita-por', title: 'italiano-português' },
  { value: 'pol-swe', title: 'język polski-Svenska' },
  { value: 'pol-fin', title: 'język polski-suomi' },
  { value: 'kur-tur', title: 'Kurdish-Turkish' },
  { value: 'ita-swe', title: 'italiano-Svenska' },
  { value: 'eng-swh', title: 'English-Swahili' },
  { value: 'kha-eng', title: 'Khasi-English' },
  { value: 'fin-eng', title: 'suomi-English' },
  { value: 'eng-hin', title: 'English-Hindi' },
  { value: 'spa-eng', title: 'Spanish-English' },
  { value: 'afr-eng', title: 'Afrikaans-English' },
  { value: 'ita-fin', title: 'italiano-suomi' },
  { value: 'eng-fin', title: 'English-suomi' },
  { value: 'fra-ita', title: 'français-italiano' },
  { value: 'deu-rus', title: 'Deutsch-Русский' },
  { value: 'deu-bul', title: 'Deutsch-български език' },
  { value: 'deu-pol', title: 'Deutsch-język polski' },
  { value: 'srp-eng', title: 'Serbian-English' },
  { value: 'kur-deu', title: 'Kurdish-German' },
  { value: 'spa-por', title: 'Spanish-Portuguese' },
  { value: 'swe-pol', title: 'Svenska-język polski' },
  { value: 'swe-rus', title: 'Svenska-Русский' },
  { value: 'nld-spa', title: 'Nederlands-español' },
  { value: 'swh-pol', title: 'Swahili-Polish' },
  { value: 'oci-cat', title: 'Lenga d\'òc-Català' },
  { value: 'ita-rus', title: 'italiano-Русский' },
  { value: 'fra-ell', title: 'français-ελληνικά' },
  { value: 'eng-srp', title: 'English-Serbian' },
  { value: 'fra-tur', title: 'français-Türkçe' },
  { value: 'fra-eng', title: 'French-English' },
  { value: 'ita-ell', title: 'italiano-ελληνικά' },
  { value: 'kur-eng', title: 'Kurdish-English' },
  { value: 'swe-deu', title: 'Svenska-Deutsch' },
  { value: 'swe-fra', title: 'Svenska-français' },
  { value: 'swe-lat', title: 'Svenska-latine' },
  { value: 'swe-ell', title: 'Svenska-ελληνικά' },
  { value: 'eng-rus', title: 'English-Russian' },
  { value: 'pol-por', title: 'język polski-português' },
  { value: 'gla-deu', title: 'Scottish Gaelic-German' },
  { value: 'eng-ita', title: 'English-Italian' },
  { value: 'pol-ita', title: 'język polski-italiano' },
  { value: 'fra-swe', title: 'français-Svenska' },
  { value: 'isl-eng', title: 'íslenska-English' },
  { value: 'swe-spa', title: 'Svenska-español' },
  { value: 'nno-nob', title: 'Norwegian Nynorsk-Norwegian' },
  { value: 'swe-ita', title: 'Svenska-italiano' },
  { value: 'fra-deu', title: 'français-Deutsch' },
  { value: 'fin-ita', title: 'suomi-italiano' },
  { value: 'nld-fra', title: 'Nederlands-French' },
  { value: 'eng-ara', title: 'English-Arabic' },
  { value: 'slk-eng', title: 'Slovak-English' },
  { value: 'fra-por', title: 'français-português' },
  { value: 'spa-ast', title: 'Spanish - Asturian' },
  { value: 'fin-jpn', title: 'suomi-日本語 (にほんご)' },
  { value: 'deu-ita', title: 'German-Italian' },
  { value: 'swh-eng', title: 'Swahili-English' },
  { value: 'fin-nor', title: 'suomi-Norsk' },
  { value: 'fra-nld', title: 'French-Dutch' },
  { value: 'lat-eng', title: 'Latin-English' },
  { value: 'eng-bul', title: 'English-български език' },
  { value: 'deu-fra', title: 'Deutsch-français' },
  { value: 'swe-bul', title: 'Svenska-български език' },
  { value: 'deu-eng', title: 'German-English' },
  { value: 'pol-rus', title: 'język polski-Русский' },
  { value: 'ita-deu', title: 'Italian-German' },
  { value: 'eng-gle', title: 'English-Irish' },
  { value: 'swe-por', title: 'Svenska-português' },
  { value: 'afr-deu', title: 'Afrikaans-German' },
  { value: 'por-deu', title: 'Portuguese-German' },
  { value: 'fra-bre', title: 'French-Breton' },
  { value: 'san-deu', title: 'Sanskrit-German' },
  { value: 'kha-deu', title: 'Khasi-German' },
  { value: 'fra-rus', title: 'français-Русский' },
  { value: 'pol-ell', title: 'język polski-ελληνικά' }
];

class Dict {
  // TODO: Setup own dictd server instead of using the public one. 
  constructor({ server = 'dict.au.dyslexicfish.net' } = {}) {
    this.server = server;
  }

  translate({ from, to, word }) {
    if (!languagePairsSupported.has(`${from}-${to}`)) {
      throw new Error(`The language pair ${from}-${to} doesn't exist.`);
    }
  
    const langPair = `fd-${from}-${to}`;

    try {
      let res = spawnSync('dict', [this.server, '-C', '-d', langPair, word]);
      res = res.stdout.toString();

      if (!res.trim().length) return null;
      return res;
    } catch (error) {
      console.error('translate', this.server, langPair, word, error);
      throw error;
    }
  }

  listDictionaries() {
    return languagePairsList;
  }
}

module.exports = {
  Dict,
}